name: Build pull request

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: gradle/actions/wrapper-validation@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1

      - uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: "gradle"

      - name: Build
        run: ./gradlew build

      - name: Build documentation
        run: ./gradlew buildDocumentation

      - name: Check repository for commits
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Build created uncommitted changes in repository"
            exit 1
          fi
