name: Build pull request

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: gradle/actions/wrapper-validation@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: "gradle"

      - name: Build
        run: ./gradlew build

      - name: Build documentation
        run: ./gradlew buildDocumentation

      - name: Check repository for commits
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Build created uncommitted changes in repository"
            exit 1
          fi
