name: Build pull request

on:
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: gradle/actions/wrapper-validation@v3

      - uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 # v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: "gradle"

      - name: Build
        run: ./gradlew build

      - name: Build documentation
        run: ./gradlew buildDocumentation

      - name: Check repository for commits
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Build created uncommitted changes in repository"
            exit 1
          fi
